<a href="https://colab.research.google.com/github/Gramani-Kumar/DL-Demo/blob/master/Tensorflow2_0_NN_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
c = tf.constant([3,4])

In [4]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [5]:
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [7]:
c.numpy()

array([3, 4], dtype=int32)

In [8]:
c.shape

TensorShape([2])

#Tensorflow 2.0 Operations


In [9]:
#create a constant
constant = tf.constant([[0,1,2,3], [5,6,7,8]])

In [10]:
constant.shape

TensorShape([2, 4])

In [13]:
constant[:,2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [14]:
#Adding 
v1 = constant + 2

In [15]:
tf.print(v1)

[[2 3 4 5]
 [7 8 9 10]]


In [16]:
#Multiplication
v2 = constant * 10
tf.print(v2)

[[0 10 20 30]
 [50 60 70 80]]


In [22]:
np.square(v2)

array([[   0,  100,  400,  900],
       [2500, 3600, 4900, 6400]], dtype=int32)

In [18]:
import numpy as np

In [20]:
np.square(v2)

array([[   0,  100,  400,  900],
       [2500, 3600, 4900, 6400]], dtype=int32)

In [21]:
#TensorFlow tensors can be used directly in the numpy functions

In [24]:
np.sqrt(np.square(v2))

array([[ 0., 10., 20., 30.],
       [50., 60., 70., 80.]])

##Dot Products

In [30]:
#np.dot(constant, constant)

In [26]:
b = tf.transpose(constant)

In [27]:
b.shape

TensorShape([4, 2])

In [28]:
np.dot(constant, b)

array([[ 14,  44],
       [ 44, 174]], dtype=int32)

##Strings

In [32]:
#String can be created used Strings
tf_string = tf.constant("myTensorFlow")

In [33]:
tf.print(tf_string)

myTensorFlow


In [34]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'myTensorFlow'>

In [36]:
tf.strings.length(tf_string).numpy()

12

In [20]:
import tensorflow as tf
import datetime
import numpy as np
from tensorflow.keras.datasets import fashion_mnist

In [22]:
(X_train, Y_train), (X_test, Y_test) = fashion_mnist.load_data()

In [23]:
X_train.shape

(60000, 28, 28)

In [24]:
X_test.shape

(10000, 28, 28)

In [25]:
#normalization
# will be in the range [0,1] 
X_train = X_train / 255.0
X_test = X_test/ 255.0

In [26]:
#Reshape it.
X_train = X_train.reshape(-1, 28*28)

In [27]:
X_test = X_test.reshape(-1, 28*28)

In [28]:
X_train.shape

(60000, 784)

In [29]:
X_test.shape

(10000, 784)

#Building an Artificial Neural Network

In [63]:
model = tf.keras.models.Sequential()

In [64]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

In [65]:
model.add(tf.keras.layers.Dropout(0.2))

In [66]:
model.add(tf.keras.layers.Dense(units=64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.1))

In [67]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [68]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [69]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 128)               100480    
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_4 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                650       
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0
_________________________________________________________________


In [45]:
tf.__version__

'2.3.0'

In [70]:
#train the model

model.fit(X_train, Y_train, epochs=5, batch_size=1)

Epoch 1/5
60000/60000 [==============================] - 84s 1ms/step - loss: 0.6153 - sparse_categorical_accuracy: 0.7821
Epoch 2/5
60000/60000 [==============================] - 81s 1ms/step - loss: 0.5309 - sparse_categorical_accuracy: 0.8169
Epoch 3/5
60000/60000 [==============================] - 82s 1ms/step - loss: 0.5278 - sparse_categorical_accuracy: 0.8256
Epoch 4/5
60000/60000 [==============================] - 82s 1ms/step - loss: 0.5135 - sparse_categorical_accuracy: 0.8271
Epoch 5/5
60000/60000 [==============================] - 81s 1ms/step - loss: 0.5198 - sparse_categorical_accuracy: 0.8302


In [36]:
(128*784 + 128)  + (128*10) + 10

101770

In [46]:
test_loss, test_accuracy = model.evaluate(X_test, Y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.5123 - sparse_categorical_accuracy: 0.8583


In [47]:
test_loss

0.5122736692428589

In [48]:
test_accuracy

0.858299970626831

In [61]:
print('Test Loss {0:6.2f}, Test Accuracy {1:2.2f}'.format (test_loss, test_accuracy))

Test Loss   0.51, Test Accuracy 0.86
